services:
  backend:
    build:
      context: ../backend
    container_name: go_backend
    restart: always
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase?sslmode=disable
    networks:
      - app-network
    depends_on:
      - db 
    ports:
      - "8080:8080"

  db:
    image: postgres:16-alpine 
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - app-network

  nginx:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.nginx
    container_name: nginx_server
    restart: always
    ports:
      - "80:80" 
    depends_on:
      - backend 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: